[
    {
        "question": "What is the use of try & catch?",
        "options": [
            "a) It is used to manually handle the exception",
            "b) It helps to fix the errors",
            "c) It prevents automatic terminating of the program in cases when an exception occurs",
            "d) All of the mentioned"
        ],
        "answer": "d",
        "explanation": "None."
    },
    {
        "question": "What will be the output of the following C# code?",
        "options": [],
        "answer": "d",
        "explanation": "finally block  execution takes place after the tryblock, no matter exception is found or not. catch block is executed only when exception is found. Here divide by zero exception is found hence both catch and finally are executed."
    },
    {
        "question": "Choose the statement which is incorrect?",
        "options": [
            "a) try block does not need to be followed by catch block",
            "b) try block can be followed by finally block instead of catch block",
            "c) try can be followed by both catch and finally block",
            "d) try need not to be followed by anything"
        ],
        "answer": "d",
        "explanation": "try followed by either catch or finally block."
    },
    {
        "question": "What will be the output of the following C# code?",
        "options": [],
        "answer": "b",
        "explanation": "None."
    },
    {
        "question": "Which of the keywords are used for the block to be examined for exceptions?",
        "options": [
            "a) try",
            "b) catch",
            "c) throw",
            "d) check"
        ],
        "answer": "a",
        "explanation": "try is used for the block that needs to be checked for the exception."
    },
    {
        "question": "Which of these keywords are used for the block to handle the exceptions generated by try block?",
        "options": [
            "a) try",
            "b) catch",
            "c) throw",
            "d) check"
        ],
        "answer": "b",
        "explanation": "None."
    },
    {
        "question": "What will be the output of the following C# code?",
        "options": [],
        "answer": "d",
        "explanation": "try should be followed by either catch or finally."
    },
    {
        "question": "What will be the output of the following C# code snippet?",
        "options": [],
        "answer": "c",
        "explanation": "finally block is always executed after try block, no matter if the exception is found or not."
    },
    {
        "question": "What will be the output of the following C# code snippet?",
        "options": [],
        "answer": "a",
        "explanation": "None."
    },
    {
        "question": "Which of these keywords are used for generating an exception manually?",
        "options": [
            "a) try",
            "b) catch",
            "c) throw",
            "d) check"
        ],
        "answer": "c",
        "explanation": "None."
    }
]